---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: Add nodejs version 13 packge 
  become: yes
  get_url:
    url: https://deb.nodesource.com/setup_13.x
    dest: /tmp/node13.sh
    mode: 100

- name: Add nodejs version 13 to apt-get
  shell: /tmp/node13.sh

- name: "install dependencies."
  become: yes
  apt:
    name: ["python3", "nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present